const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..', '..');
const names = ['common', 'settings', 'assets', 'results', 'protocol', 'benchmark-summary'];
const body = names.map(name => {
  const text = fs.readFileSync(path.join(root, 'spec/schemas', `${name}.schema.json`), 'utf8').replace(/\r\n/g, '\n');
  return `    {"${name === 'benchmark-summary' ? 'benchmark_summary' : name}", R"schema(${text})schema"},`;
}).join('\n');
const output = `// Generated by tools/contracts/embed-schemas.cjs; do not edit.\n#pragma once\n#include <map>\n#include <string>\nnamespace spectrapack::io::detail {\ninline const std::map<std::string, std::string> kEmbeddedSchemas = {\n${body}\n};\n}\n`;
const target = path.join(root, 'engine/pack_io/src/embedded_schemas.hpp');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== output) { console.error('embedded schema header is stale; run node tools/contracts/embed-schemas.cjs'); process.exit(1); }
} else fs.writeFileSync(target, output);
