const fs = require('fs');
const path = require('path');
const { compile } = require('json-schema-to-typescript');

const root = path.resolve(__dirname, '..', '..');
const schemaRoot = path.join(root, 'spec/schemas');
const target = path.join(root, 'desktop/src/generated/contracts.ts');
const files = [
  ['Common', 'common'],
  ['Settings', 'settings'],
  ['Assets', 'assets'],
  ['Results', 'results'],
  ['Protocol', 'protocol'],
  ['BenchmarkSummary', 'benchmark-summary'],
];

function normalizeLf(value) {
  return value.replace(/\r\n?/g, '\n');
}

function loadCatalog() {
  const catalog = new Map();
  for (const [, file] of files) {
    const text = normalizeLf(fs.readFileSync(path.join(schemaRoot, `${file}.schema.json`), 'utf8'));
    const schema = JSON.parse(text);
    const expectedId = `https://spectrapack.invalid/schemas/v1/${file}.schema.json`;
    if (schema.$id !== expectedId) {
      throw new Error(`${file}.schema.json has unexpected $id ${JSON.stringify(schema.$id)}`);
    }
    if (catalog.has(schema.$id)) {
      throw new Error(`duplicate schema $id ${schema.$id}`);
    }
    // Store immutable text. $RefParser parses a fresh document for each read, so
    // one compilation cannot mutate catalog objects used by the next.
    catalog.set(schema.$id, JSON.stringify(schema));
  }
  return catalog;
}

function closedRefOptions(catalog) {
  return {
    mutateInputSchema: false,
    resolve: {
      external: true,
      file: false,
      http: false,
      catalog: {
        order: 1,
        canRead(file) {
          return catalog.has(file.url);
        },
        read(file) {
          const text = catalog.get(file.url);
          if (text === undefined) {
            throw new Error(`schema is outside the closed catalog: ${file.url}`);
          }
          return text;
        },
      },
    },
  };
}

(async () => {
  const catalog = loadCatalog();
  const refOptions = closedRefOptions(catalog);
  const declarations = [];

  for (const [namespace, file] of files) {
    const id = `https://spectrapack.invalid/schemas/v1/${file}.schema.json`;
    const schema = JSON.parse(catalog.get(id));
    const output = await compile(schema, namespace, {
      bannerComment: '',
      unreachableDefinitions: true,
      unknownAny: true,
      cwd: schemaRoot,
      $refOptions: refOptions,
    });
    declarations.push(`export namespace ${namespace} {\n${output}\n}`);
  }

  const generated = normalizeLf(
    `/* Generated by tools/contracts/generate-types.cjs; do not edit. */\n\n${declarations.join('\n\n')}\n`,
  );
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(target) ? normalizeLf(fs.readFileSync(target, 'utf8')) : '';
    if (current !== generated) {
      console.error('generated TypeScript is stale; run node tools/contracts/generate-types.cjs');
      process.exit(1);
    }
  } else {
    fs.writeFileSync(target, generated);
  }
})().catch(error => {
  console.error(error);
  process.exit(1);
});
