// Generated by tools/contracts/embed-schemas.cjs; do not edit.
#pragma once
#include <map>
#include <string>
namespace spectrapack::io::detail {
inline const std::map<std::string, std::string> kEmbeddedSchemas = {
    {"common", R"schema({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://spectrapack.invalid/schemas/v1/common.schema.json",
  "definitions": {
    "counter": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "positive": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "nonnegative": {
      "type": "number",
      "minimum": 0
    },
    "vec3": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 3,
      "maxItems": 3
    },
    "quaternion": {
      "type": "array",
      "items": {
        "type": "number"
      },
      "minItems": 4,
      "maxItems": 4
    },
    "matrix4": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        },
        "minItems": 4,
        "maxItems": 4
      },
      "minItems": 4,
      "maxItems": 4
    },
    "sha256": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "portable_path": {
      "type": "string",
      "minLength": 1,
      "not": {
        "pattern": "(^[A-Za-z]:|^/|^\\\\|\\\\|(^|/)\\.{1,2}(/|$)|\\x00)"
      }
    },
    "runtime_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128,
      "pattern": "^[^\\x00]+$"
    },
    "seed": {
      "type": "string",
      "pattern": "^(0|[1-9][0-9]{0,19})$"
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "clearance": {
      "type": "object",
      "required": [
        "pair",
        "wall"
      ],
      "properties": {
        "pair": {
          "$ref": "#/definitions/nonnegative"
        },
        "wall": {
          "$ref": "#/definitions/nonnegative"
        }
      },
      "additionalProperties": false
    },
    "error": {
      "type": "object",
      "required": [
        "code",
        "message",
        "details",
        "recoverable"
      ],
      "properties": {
        "code": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        },
        "message": {
          "type": "string",
          "minLength": 1
        },
        "details": {
          "type": "object"
        },
        "recoverable": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "content_ref": {
      "type": "object",
      "required": [
        "source_sha256",
        "accepted_solid_sha256"
      ],
      "properties": {
        "source_sha256": {
          "$ref": "#/definitions/sha256"
        },
        "accepted_solid_sha256": {
          "$ref": "#/definitions/sha256"
        }
      },
      "additionalProperties": false
    }
  }
}
)schema"},
    {"settings", R"schema({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://spectrapack.invalid/schemas/v1/settings.schema.json",
  "definitions": {
    "q": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/quaternion"
    },
    "box": {
      "type": "object",
      "required": [
        "kind",
        "dimensions_mm"
      ],
      "properties": {
        "kind": {
          "const": "box"
        },
        "dimensions_mm": {
          "type": "array",
          "items": {
            "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/positive"
          },
          "minItems": 3,
          "maxItems": 3
        }
      },
      "additionalProperties": false
    },
    "stl_id": {
      "type": "object",
      "required": [
        "kind",
        "asset_id"
      ],
      "properties": {
        "kind": {
          "const": "stl_volume"
        },
        "asset_id": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/runtime_id"
        }
      },
      "additionalProperties": false
    },
    "stl_ref": {
      "type": "object",
      "required": [
        "kind",
        "asset"
      ],
      "properties": {
        "kind": {
          "const": "stl_volume"
        },
        "asset": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/content_ref"
        }
      },
      "additionalProperties": false
    },
    "or_requested": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "mode"
          ],
          "properties": {
            "mode": {
              "const": "fixed"
            },
            "quaternion_xyzw": {
              "$ref": "#/definitions/q"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode"
          ],
          "properties": {
            "mode": {
              "enum": [
                "upright",
                "cube"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode",
            "catalog_size"
          ],
          "properties": {
            "mode": {
              "const": "free"
            },
            "catalog_size": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode",
            "quaternions_xyzw"
          ],
          "properties": {
            "mode": {
              "const": "custom"
            },
            "quaternions_xyzw": {
              "type": "array",
              "minItems": 1,
              "items": {
                "$ref": "#/definitions/q"
              }
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "or_resolved": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "mode",
            "quaternion_xyzw"
          ],
          "properties": {
            "mode": {
              "const": "fixed"
            },
            "quaternion_xyzw": {
              "$ref": "#/definitions/q"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode"
          ],
          "properties": {
            "mode": {
              "enum": [
                "upright",
                "cube"
              ]
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode",
            "catalog_size"
          ],
          "properties": {
            "mode": {
              "const": "free"
            },
            "catalog_size": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode",
            "quaternions_xyzw"
          ],
          "properties": {
            "mode": {
              "const": "custom"
            },
            "quaternions_xyzw": {
              "type": "array",
              "minItems": 1,
              "items": {
                "$ref": "#/definitions/q"
              }
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "search": {
      "type": "object",
      "required": [
        "preset",
        "seed",
        "deterministic"
      ],
      "properties": {
        "preset": {
          "type": "string",
          "minLength": 1
        },
        "seed": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/seed"
        },
        "deterministic": {
          "type": "boolean"
        },
        "budget_seconds": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/positive"
        },
        "work_budget": {
          "type": "object",
          "required": [
            "max_candidate_evaluations",
            "max_search_passes"
          ],
          "properties": {
            "max_candidate_evaluations": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            },
            "max_search_passes": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "resolution": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "mode",
            "longest_object_axis_cells"
          ],
          "properties": {
            "mode": {
              "const": "auto"
            },
            "longest_object_axis_cells": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "mode",
            "pitch_mm"
          ],
          "properties": {
            "mode": {
              "const": "manual"
            },
            "pitch_mm": {
              "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/positive"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "compute": {
      "type": "object",
      "required": [
        "backend"
      ],
      "properties": {
        "backend": {
          "enum": [
            "auto",
            "cpu",
            "vulkan"
          ]
        }
      },
      "additionalProperties": false
    },
    "requested": {
      "type": "object",
      "required": [
        "settings_version",
        "object_asset_id",
        "container",
        "clearance_mm",
        "orientation",
        "search",
        "resolution",
        "compute"
      ],
      "properties": {
        "settings_version": {
          "const": 1
        },
        "object_asset_id": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/runtime_id"
        },
        "container": {
          "oneOf": [
            {
              "$ref": "#/definitions/box"
            },
            {
              "$ref": "#/definitions/stl_id"
            }
          ]
        },
        "clearance_mm": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/clearance"
        },
        "orientation": {
          "$ref": "#/definitions/or_requested"
        },
        "search": {
          "$ref": "#/definitions/search"
        },
        "resolution": {
          "$ref": "#/definitions/resolution"
        },
        "compute": {
          "$ref": "#/definitions/compute"
        }
      },
      "additionalProperties": false
    },
    "resolved": {
      "type": "object",
      "required": [
        "settings_version",
        "object_asset",
        "container",
        "clearance_mm",
        "orientation",
        "search",
        "resolution",
        "compute",
        "resolved"
      ],
      "properties": {
        "settings_version": {
          "const": 1
        },
        "object_asset": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/content_ref"
        },
        "container": {
          "oneOf": [
            {
              "$ref": "#/definitions/box"
            },
            {
              "$ref": "#/definitions/stl_ref"
            }
          ]
        },
        "clearance_mm": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/clearance"
        },
        "orientation": {
          "$ref": "#/definitions/or_resolved"
        },
        "search": {
          "$ref": "#/definitions/search"
        },
        "resolution": {
          "$ref": "#/definitions/resolution"
        },
        "compute": {
          "$ref": "#/definitions/compute"
        },
        "resolved": {
          "type": "object",
          "required": [
            "pitch_mm",
            "orientation_catalog_sha256",
            "orientation_catalog_version",
            "backend",
            "thread_count"
          ],
          "properties": {
            "pitch_mm": {
              "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/positive"
            },
            "orientation_catalog_sha256": {
              "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/sha256"
            },
            "orientation_catalog_version": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            },
            "backend": {
              "enum": [
                "cpu",
                "vulkan"
              ]
            },
            "thread_count": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9007199254740991
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "oneOf": [
    {
      "$ref": "#/definitions/requested"
    },
    {
      "$ref": "#/definitions/resolved"
    }
  ]
}
)schema"},
    {"assets", R"schema({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://spectrapack.invalid/schemas/v1/assets.schema.json",
  "definitions": {
    "hash": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/sha256"
    },
    "path": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/portable_path"
    },
    "source": {
      "type": "object",
      "required": [
        "sha256",
        "path",
        "units",
        "unit_scale_mm"
      ],
      "properties": {
        "sha256": {
          "$ref": "#/definitions/hash"
        },
        "path": {
          "$ref": "#/definitions/path"
        },
        "units": {
          "enum": [
            "mm",
            "inch",
            "custom"
          ]
        },
        "unit_scale_mm": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/positive"
        }
      },
      "additionalProperties": false
    },
    "frame": {
      "type": "object",
      "required": [
        "source_bounds",
        "source_to_local"
      ],
      "properties": {
        "source_bounds": {
          "type": "object",
          "required": [
            "min",
            "max"
          ],
          "properties": {
            "min": {
              "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/vec3"
            },
            "max": {
              "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/vec3"
            }
          },
          "additionalProperties": false
        },
        "source_to_local": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/matrix4"
        }
      },
      "additionalProperties": false
    },
    "diagnostics": {
      "type": "object",
      "required": [
        "status",
        "messages"
      ],
      "properties": {
        "status": {
          "enum": [
            "valid",
            "invalid",
            "indeterminate"
          ]
        },
        "messages": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false
    },
    "solid": {
      "type": "object",
      "required": [
        "sha256",
        "path",
        "format",
        "vertex_count",
        "triangle_count"
      ],
      "properties": {
        "sha256": {
          "$ref": "#/definitions/hash"
        },
        "path": {
          "$ref": "#/definitions/path"
        },
        "format": {
          "const": "binary_little_endian_ply_f64_u32"
        },
        "vertex_count": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/counter"
        },
        "triangle_count": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/counter"
        }
      },
      "additionalProperties": false
    },
    "repair": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "required": [
            "path",
            "sha256",
            "accepted_by_user"
          ],
          "properties": {
            "path": {
              "$ref": "#/definitions/path"
            },
            "sha256": {
              "$ref": "#/definitions/hash"
            },
            "accepted_by_user": {
              "const": true
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "preview": {
      "type": "object",
      "required": [
        "path",
        "sha256"
      ],
      "properties": {
        "path": {
          "$ref": "#/definitions/path"
        },
        "sha256": {
          "$ref": "#/definitions/hash"
        }
      },
      "additionalProperties": false
    },
    "base": {
      "type": "object",
      "required": [
        "schema_version",
        "role",
        "state",
        "source",
        "frame",
        "dimensions_mm",
        "diagnostics"
      ],
      "properties": {
        "schema_version": {
          "const": 1
        },
        "role": {
          "enum": [
            "object",
            "container"
          ]
        },
        "state": {
          "enum": [
            "inspected",
            "accepted"
          ]
        },
        "source": {
          "$ref": "#/definitions/source"
        },
        "frame": {
          "$ref": "#/definitions/frame"
        },
        "dimensions_mm": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/vec3"
        },
        "diagnostics": {
          "$ref": "#/definitions/diagnostics"
        },
        "accepted_solid": {
          "$ref": "#/definitions/solid"
        },
        "repair_record": {
          "$ref": "#/definitions/repair"
        },
        "preview": {
          "$ref": "#/definitions/preview"
        }
      },
      "additionalProperties": false
    },
    "inspected": {
      "allOf": [
        {
          "$ref": "#/definitions/base"
        },
        {
          "properties": {
            "state": {
              "const": "inspected"
            }
          }
        },
        {
          "not": {
            "anyOf": [
              {
                "required": [
                  "accepted_solid"
                ]
              },
              {
                "required": [
                  "repair_record"
                ]
              }
            ]
          }
        }
      ]
    },
    "accepted": {
      "allOf": [
        {
          "$ref": "#/definitions/base"
        },
        {
          "required": [
            "accepted_solid",
            "repair_record"
          ],
          "properties": {
            "state": {
              "const": "accepted"
            },
            "diagnostics": {
              "allOf": [
                {
                  "$ref": "#/definitions/diagnostics"
                },
                {
                  "properties": {
                    "status": {
                      "const": "valid"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  },
  "oneOf": [
    {
      "$ref": "#/definitions/inspected"
    },
    {
      "$ref": "#/definitions/accepted"
    }
  ]
}
)schema"},
    {"results", R"schema({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://spectrapack.invalid/schemas/v1/results.schema.json",
  "definitions": {
    "c": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/counter"
    },
    "q": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/quaternion"
    },
    "m": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/matrix4"
    },
    "hash": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/sha256"
    },
    "work": {
      "type": "object",
      "required": [
        "candidate_evaluations",
        "search_passes"
      ],
      "properties": {
        "candidate_evaluations": {
          "$ref": "#/definitions/c"
        },
        "search_passes": {
          "$ref": "#/definitions/c"
        }
      },
      "additionalProperties": false
    },
    "segment": {
      "type": "object",
      "required": [
        "segment_id",
        "parent_solution_revision",
        "seed",
        "backend",
        "elapsed_seconds",
        "work_counts",
        "search_state_reset",
        "rng",
        "resolved_settings"
      ],
      "properties": {
        "segment_id": {
          "type": "string",
          "minLength": 1
        },
        "parent_solution_revision": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/c"
            }
          ]
        },
        "seed": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/seed"
        },
        "backend": {
          "enum": [
            "cpu",
            "vulkan"
          ]
        },
        "elapsed_seconds": {
          "type": "number",
          "minimum": 0
        },
        "work_counts": {
          "$ref": "#/definitions/work"
        },
        "search_state_reset": {
          "type": "boolean"
        },
        "rng": {
          "type": "object",
          "required": [
            "algorithm",
            "state"
          ],
          "properties": {
            "algorithm": {
              "type": "string",
              "minLength": 1
            },
            "state": {
              "type": "string",
              "minLength": 1
            }
          },
          "additionalProperties": false
        },
        "resolved_settings": {
          "$ref": "https://spectrapack.invalid/schemas/v1/settings.schema.json#/definitions/resolved"
        }
      },
      "additionalProperties": false
    },
    "placement": {
      "type": "object",
      "required": [
        "copy_id",
        "translation_mm",
        "quaternion_xyzw",
        "local_to_world"
      ],
      "properties": {
        "copy_id": {
          "type": "string",
          "minLength": 1
        },
        "translation_mm": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/vec3"
        },
        "quaternion_xyzw": {
          "$ref": "#/definitions/q"
        },
        "local_to_world": {
          "$ref": "#/definitions/m"
        }
      },
      "additionalProperties": false
    },
    "transition": {
      "type": "object",
      "required": [
        "segment_id",
        "from",
        "to",
        "reason",
        "elapsed_seconds"
      ],
      "properties": {
        "segment_id": {
          "type": "string",
          "minLength": 1
        },
        "from": {
          "enum": [
            "cpu",
            "vulkan"
          ]
        },
        "to": {
          "enum": [
            "cpu",
            "vulkan"
          ]
        },
        "reason": {
          "type": "string",
          "minLength": 1
        },
        "elapsed_seconds": {
          "type": "number",
          "minimum": 0
        },
        "device": {
          "type": "string"
        },
        "driver": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "type": "object",
  "required": [
    "schema_version",
    "label",
    "job_id",
    "solution_revision",
    "created_at",
    "engine",
    "assets",
    "container",
    "constraints",
    "search",
    "count",
    "placements",
    "validation",
    "metrics"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "label": {
      "const": "best_found"
    },
    "job_id": {
      "type": "string",
      "minLength": 1
    },
    "solution_revision": {
      "$ref": "#/definitions/c"
    },
    "created_at": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/timestamp"
    },
    "engine": {
      "type": "object",
      "required": [
        "version",
        "commit"
      ],
      "properties": {
        "version": {
          "type": "string"
        },
        "commit": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "assets": {
      "type": "object",
      "required": [
        "object"
      ],
      "properties": {
        "object": {
          "$ref": "https://spectrapack.invalid/schemas/v1/assets.schema.json#/definitions/accepted"
        },
        "container": {
          "$ref": "https://spectrapack.invalid/schemas/v1/assets.schema.json#/definitions/accepted"
        }
      },
      "additionalProperties": false
    },
    "container": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "kind",
            "dimensions_mm"
          ],
          "properties": {
            "kind": {
              "const": "box"
            },
            "dimensions_mm": {
              "type": "array",
              "items": {
                "type": "number",
                "exclusiveMinimum": 0
              },
              "minItems": 3,
              "maxItems": 3
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "kind",
            "asset",
            "source_to_world",
            "semantics"
          ],
          "properties": {
            "kind": {
              "const": "stl_volume"
            },
            "asset": {
              "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/content_ref"
            },
            "source_to_world": {
              "$ref": "#/definitions/m"
            },
            "semantics": {
              "const": "interior_volume"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "constraints": {
      "type": "object",
      "required": [
        "clearance_mm",
        "orientation",
        "orientation_catalog_sha256"
      ],
      "properties": {
        "clearance_mm": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/clearance"
        },
        "orientation": {
          "$ref": "https://spectrapack.invalid/schemas/v1/settings.schema.json#/definitions/or_resolved"
        },
        "orientation_catalog_sha256": {
          "$ref": "#/definitions/hash"
        }
      },
      "additionalProperties": false
    },
    "search": {
      "type": "object",
      "required": [
        "resolved_settings",
        "pitch_levels_mm",
        "seed",
        "work_counts",
        "run_segments",
        "backend_transitions",
        "elapsed_seconds"
      ],
      "properties": {
        "resolved_settings": {
          "$ref": "https://spectrapack.invalid/schemas/v1/settings.schema.json#/definitions/resolved"
        },
        "pitch_levels_mm": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "number",
            "exclusiveMinimum": 0
          }
        },
        "seed": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/seed"
        },
        "work_counts": {
          "$ref": "#/definitions/work"
        },
        "run_segments": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/segment"
          }
        },
        "backend_transitions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/transition"
          }
        },
        "elapsed_seconds": {
          "type": "number",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "count": {
      "$ref": "#/definitions/c"
    },
    "placements": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/placement"
      }
    },
    "validation": {
      "type": "object",
      "required": [
        "status",
        "tolerance_mm",
        "authoritative_geometry_sha256",
        "validator_version",
        "kernel_version",
        "checks"
      ],
      "properties": {
        "status": {
          "const": "valid"
        },
        "tolerance_mm": {
          "type": "number",
          "minimum": 0
        },
        "authoritative_geometry_sha256": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/hash"
          }
        },
        "validator_version": {
          "type": "string"
        },
        "kernel_version": {
          "type": "string"
        },
        "checks": {
          "type": "object",
          "required": [
            "pair",
            "containment",
            "clearance"
          ],
          "properties": {
            "pair": {
              "const": "valid"
            },
            "containment": {
              "const": "valid"
            },
            "clearance": {
              "const": "valid"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "metrics": {
      "type": "object",
      "required": [
        "solid_volume_mm3",
        "container_volume_mm3",
        "utilization",
        "time_to_best_seconds",
        "peak_host_bytes",
        "peak_device_bytes",
        "termination_reason"
      ],
      "properties": {
        "solid_volume_mm3": {
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0
        },
        "container_volume_mm3": {
          "type": [
            "number",
            "null"
          ],
          "exclusiveMinimum": 0
        },
        "utilization": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 1
        },
        "time_to_best_seconds": {
          "type": "number",
          "minimum": 0
        },
        "peak_host_bytes": {
          "$ref": "#/definitions/c"
        },
        "peak_device_bytes": {
          "$ref": "#/definitions/c"
        },
        "termination_reason": {
          "enum": [
            "budget_exhausted",
            "user_stopped",
            "search_stalled",
            "resource_limit",
            "error"
          ]
        }
      },
      "additionalProperties": false
    },
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "kind",
          "path",
          "sha256"
        ],
        "properties": {
          "kind": {
            "enum": [
              "assembled_stl",
              "preview_image",
              "benchmark",
              "log"
            ]
          },
          "path": {
            "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/portable_path"
          },
          "sha256": {
            "$ref": "#/definitions/hash"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}
)schema"},
    {"protocol", R"schema({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://spectrapack.invalid/schemas/v1/protocol.schema.json",
  "definitions": {
    "id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128,
      "not": {
        "pattern": "\\x00"
      }
    },
    "request": {
      "type": "object",
      "required": [
        "protocol_version",
        "request_id",
        "method",
        "params"
      ],
      "properties": {
        "protocol_version": {
          "const": 1
        },
        "request_id": {
          "$ref": "#/definitions/id"
        },
        "method": {
          "$ref": "#/definitions/id"
        },
        "params": {
          "type": "object"
        }
      },
      "additionalProperties": false
    },
    "success": {
      "type": "object",
      "required": [
        "protocol_version",
        "request_id",
        "ok",
        "result"
      ],
      "properties": {
        "protocol_version": {
          "const": 1
        },
        "request_id": {
          "$ref": "#/definitions/id"
        },
        "ok": {
          "const": true
        },
        "result": {}
      },
      "additionalProperties": false
    },
    "failure": {
      "type": "object",
      "required": [
        "protocol_version",
        "request_id",
        "ok",
        "error"
      ],
      "properties": {
        "protocol_version": {
          "const": 1
        },
        "request_id": {
          "anyOf": [
            {
              "$ref": "#/definitions/id"
            },
            {
              "type": "null"
            }
          ]
        },
        "ok": {
          "const": false
        },
        "error": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/error"
        }
      },
      "additionalProperties": false
    },
    "event": {
      "type": "object",
      "required": [
        "protocol_version",
        "job_id",
        "sequence",
        "type",
        "payload"
      ],
      "properties": {
        "protocol_version": {
          "const": 1
        },
        "job_id": {
          "$ref": "#/definitions/id"
        },
        "sequence": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/counter"
        },
        "type": {
          "enum": [
            "task_progress",
            "job_state",
            "best_solution",
            "backend_changed",
            "warning",
            "error",
            "job_finished"
          ]
        },
        "payload": {}
      },
      "additionalProperties": false
    }
  },
  "oneOf": [
    {
      "$ref": "#/definitions/request"
    },
    {
      "$ref": "#/definitions/success"
    },
    {
      "$ref": "#/definitions/failure"
    },
    {
      "$ref": "#/definitions/event"
    }
  ]
}
)schema"},
    {"benchmark_summary", R"schema({
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://spectrapack.invalid/schemas/v1/benchmark-summary.schema.json",
  "definitions": {
    "counter": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/counter"
    },
    "timings": {
      "type": "object",
      "required": [
        "preprocessing_seconds",
        "search_seconds",
        "validation_seconds",
        "export_seconds",
        "cold_end_to_end_seconds"
      ],
      "properties": {
        "preprocessing_seconds": {
          "type": "number",
          "minimum": 0
        },
        "search_seconds": {
          "type": "number",
          "minimum": 0
        },
        "validation_seconds": {
          "type": "number",
          "minimum": 0
        },
        "export_seconds": {
          "type": "number",
          "minimum": 0
        },
        "cold_end_to_end_seconds": {
          "type": "number",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "transition": {
      "type": "object",
      "required": [
        "segment_id",
        "from",
        "to",
        "reason",
        "elapsed_seconds"
      ],
      "properties": {
        "segment_id": {
          "type": "string",
          "minLength": 1
        },
        "from": {
          "enum": [
            "cpu",
            "vulkan"
          ]
        },
        "to": {
          "enum": [
            "cpu",
            "vulkan"
          ]
        },
        "reason": {
          "type": "string",
          "minLength": 1
        },
        "elapsed_seconds": {
          "type": "number",
          "minimum": 0
        },
        "device": {
          "type": "string"
        },
        "driver": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "result": {
      "type": "object",
      "required": [
        "path",
        "sha256"
      ],
      "properties": {
        "path": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/portable_path"
        },
        "sha256": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/sha256"
        }
      },
      "additionalProperties": false
    },
    "run": {
      "type": "object",
      "required": [
        "seed",
        "status",
        "settings",
        "count",
        "result",
        "validation_failures",
        "timings",
        "peak_host_bytes",
        "peak_device_bytes",
        "improvements",
        "backend_transitions"
      ],
      "properties": {
        "seed": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/seed"
        },
        "status": {
          "enum": [
            "completed",
            "failed"
          ]
        },
        "settings": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "https://spectrapack.invalid/schemas/v1/settings.schema.json#/definitions/resolved"
            }
          ]
        },
        "count": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/counter"
            }
          ]
        },
        "result": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/result"
            }
          ]
        },
        "validation_failures": {
          "$ref": "#/definitions/counter"
        },
        "timings": {
          "$ref": "#/definitions/timings"
        },
        "peak_host_bytes": {
          "$ref": "#/definitions/counter"
        },
        "peak_device_bytes": {
          "$ref": "#/definitions/counter"
        },
        "improvements": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "count",
              "elapsed_seconds"
            ],
            "properties": {
              "count": {
                "$ref": "#/definitions/counter"
              },
              "elapsed_seconds": {
                "type": "number",
                "minimum": 0
              }
            },
            "additionalProperties": false
          }
        },
        "backend_transitions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/transition"
          }
        },
        "error": {
          "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/error"
        }
      },
      "additionalProperties": false,
      "allOf": [
        {
          "if": {
            "properties": {
              "status": {
                "const": "completed"
              }
            }
          },
          "then": {
            "required": [
              "settings",
              "count",
              "result"
            ],
            "properties": {
              "settings": {
                "$ref": "https://spectrapack.invalid/schemas/v1/settings.schema.json#/definitions/resolved"
              },
              "count": {
                "$ref": "#/definitions/counter"
              },
              "result": {
                "$ref": "#/definitions/result"
              },
              "validation_failures": {
                "const": 0
              },
              "error": {
                "not": {}
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "status": {
                "const": "failed"
              }
            }
          },
          "then": {
            "required": [
              "error"
            ]
          }
        }
      ]
    }
  },
  "type": "object",
  "required": [
    "schema_version",
    "suite_id",
    "created_at",
    "engine",
    "host",
    "dependency_revisions",
    "configuration",
    "runs",
    "summary"
  ],
  "properties": {
    "schema_version": {
      "const": 1
    },
    "suite_id": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "$ref": "https://spectrapack.invalid/schemas/v1/common.schema.json#/definitions/timestamp"
    },
    "engine": {
      "type": "object",
      "required": [
        "version",
        "commit"
      ],
      "properties": {
        "version": {
          "type": "string"
        },
        "commit": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "host": {
      "type": "object",
      "required": [
        "cpu",
        "gpu",
        "driver",
        "os_build",
        "thread_count"
      ],
      "properties": {
        "cpu": {
          "type": "string"
        },
        "gpu": {
          "type": [
            "string",
            "null"
          ]
        },
        "driver": {
          "type": [
            "string",
            "null"
          ]
        },
        "os_build": {
          "type": "string"
        },
        "thread_count": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        }
      },
      "additionalProperties": false
    },
    "dependency_revisions": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "type": "string"
      }
    },
    "configuration": {
      "type": "object",
      "required": [
        "method",
        "settings",
        "cache_state"
      ],
      "properties": {
        "method": {
          "enum": [
            "aabb",
            "greedy_spectral",
            "full_search"
          ]
        },
        "settings": {
          "$ref": "https://spectrapack.invalid/schemas/v1/settings.schema.json#/definitions/resolved"
        },
        "cache_state": {
          "enum": [
            "cold",
            "warm"
          ]
        }
      },
      "additionalProperties": false
    },
    "runs": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/run"
      }
    },
    "summary": {
      "type": "object",
      "required": [
        "successful_runs",
        "failed_runs",
        "best_count",
        "median_count",
        "worst_count"
      ],
      "properties": {
        "successful_runs": {
          "$ref": "#/definitions/counter"
        },
        "failed_runs": {
          "$ref": "#/definitions/counter"
        },
        "best_count": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/counter"
            }
          ]
        },
        "median_count": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0
        },
        "worst_count": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/counter"
            }
          ]
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}
)schema"},
};
}
